---
title: "E155 Project"
---

This project implements hang gesture recognition to complete a human-vs-computer rock–paper–scissors system. Five time-multiplexed VL53L0X LiDAR modules embedded beneath a constrained scanning platform capture hand pose signatures, enabling classification of rock, paper, and scissors while mitigating cross-sensor interference and off-angle reflection loss. An FPGA drives an LCD display for real-time game feedback, and interfaces with an MCU that executes the computer’s move logic. The design’s primary technical challenge lies in achieving reliable gesture discrimination across diverse users through precise synchronized ranging and signal integration.

As an extension to this project, I will be pursuing my own investigation into the Lattice SensAI Demo for Hand Gesture Detection. This is an FPGA based AI implementation of hand gesture recognition through the compact on-board CNN.

## Project Proposal
[Project Proposal](project/projectproposal.qmd)

## Midway Check-In
[MidWay Check In](project/midwaycheckin.qmd)

## Project Extension
[Project Extension](project/projectextension.qmd)